seq_len = 131072

[log]
level = "debug"

[model]
name = "Qwen/Qwen3-30B-A3B-Thinking-2507"

[trainer.tokenizer]
name = "Qwen/Qwen3-30B-A3B-Thinking-2507"

[weight_broadcast]
type = "nccl"

[deployment]
type = "multi_node"
num_train_nodes = 1
num_infer_nodes = 1

[slurm]
job_name = "swe-qwen30b"
partition = "main"

[ckpt]
interval = 100

[wandb]
project = "qwen30b-swe"

[trainer.model]
impl = "custom"
attn = "flash_attention_2"
fused_lm_head_token_chunk_size = 1024
ep = 8
cp = 2
optim_cpu_offload = true

[trainer.model.compile]

[trainer.model.ac_offloading]
max_inflight_activations = 5

[trainer.model.ac]
freq = 1

[trainer.optim]
type = "adamw"
lr = 1e-6

[orchestrator]
batch_size = 128
oversampling_factor = 1.5
max_off_policy_steps = 16

[[orchestrator.env]]
id = "mini-swe-agent-plus"
name = "swe"
args = { max_turns = 200, cpu_cores = 2,  memory_gb = 4, disk_size_gb = 4, labels = ["mini-swe-agent-plus"], total_timeout_minutes = 720, sandbox_client_max_workers = 256, max_command_timeouts = 3, sandbox_command_timeout = 30}

[orchestrator.eval]
interval = 25
eval_base_model = false

[[orchestrator.eval.env]]
id = "mini-swe-agent-plus"
name = "swe-bench-verified-quick"
args = { dataset_name="PrimeIntellect/SWE-Bench-Verified-Quick", max_turns = 200, cpu_cores = 2,  memory_gb = 4, disk_size_gb = 4, labels = ["mini-swe-agent-plus"], total_timeout_minutes = 720, sandbox_client_max_workers = 256, max_command_timeouts = 3, sandbox_command_timeout = 30}

[orchestrator.buffer]
easy_threshold = 1.0
hard_threshold = 0.0
seed = 42

[inference]
use_deep_gemm = false

[inference.model]
tool_call_parser = "auto"

[inference.parallel]
tp = 8
